[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust"
crate-type = ["cdylib"]

[dependencies]
sudoku = "0.7.0"
pyo3 = { version = "0.17.3", features = ["extension-module"] }
